// Purpose: This query imports the latest Excel sheet from a specified folder, promotes headers, adds a column with the file's modification date, and outputs the data.

//Step 1: Retrieve the file path from the named range "FolderPath" in the current workbook.

//Step 2: Get the list of files in the folder and filter out the current file.

//Step 3: Add a custom column to extract the file modification date and sort the files by modification date.

//Step 4: Get the latest file and construct its path.

//Step 5: Extract the sheet name from the latest file name by removing the ".xlsx" extension.

//Step 6: Import the latest Excel workbook and get the data from the specific sheet.

//Step 7: Add the "DataSourceDate" column with the modified date in "dd-mm-yy" format and set its type to date.



let
    // Step 1: Retrieve the file path from the named range "FolderPath" in the current workbook
    FolderPath = Excel.CurrentWorkbook(){[Name="FolderPath"]}[Content]{0}[Column1],
    
    // Step 2: Get the list of files in the folder and filter out the current file
    Source = Table.Buffer(Folder.Files(FolderPath)),
    CurrentWorkbookName = Text.BeforeDelimiter(FolderPath, ".xlsx"),
    FilteredFiles = Table.SelectRows(Source, each Text.BeforeDelimiter([Name], ".") <> CurrentWorkbookName),
    
    // Step 3: Add a custom column to extract the file modification date and sort by modification date
    AddDateColumn = Table.AddColumn(FilteredFiles, "Date_Modified", each DateTime.From([#"Date modified"]), type datetime),
    SortedTable = Table.Sort(AddDateColumn, {{"Date_Modified", Order.Descending}}),
    
    // Step 4: Get the latest file and its path
    LatestFile = Table.FirstN(SortedTable, 1),
    LatestFilePath = FolderPath & "\" & LatestFile{0}[Name],
    
    // Step 5: Extract the sheet name from the latest file name
    SheetName = Text.BeforeDelimiter(LatestFile{0}[Name], ".xlsx"),
    
    // Step 6: Import the latest Excel workbook and get the specific sheet data
    SheetData = Excel.Workbook(File.Contents(LatestFilePath)){[Item=SheetName, Kind="Sheet"]}[Data],
    PromotedHeaders = Table.PromoteHeaders(SheetData, [PromoteAllScalars=true]),

    // Step 7: Add the "DataSourceDate" column with the modified date in "dd-mm-yy" format and change type
    AddDateSourcedate = Table.AddColumn(PromotedHeaders, "DataSourceDate", each Date.ToText(DateTime.Date(LatestFile{0}[#"Date modified"]), "dd-MM-yy")),
    ChangedType = Table.TransformColumnTypes(AddDateSourcedate,{{"DataSourceDate", type date}})
in
    // Output the final table with the promoted headers and added "DataSourceDate" column
    ChangedType

