// LatestFileDataLoader
// This Power Query M code retrieves the latest file from a specified folder, dynamically counts the number of columns in a CSV file (if applicable), loads the data, promotes headers, and adds a "DataSourceDate" column with the file's modified date.

let
    // Step 1: Retrieve the file path from the named range "FolderPath" in the current workbook
    FolderPath = Excel.CurrentWorkbook(){[Name="FolderPath"]}[Content]{0}[Column1],
    
    // Step 2: Get the list of files in the folder
    Source = Folder.Files(FolderPath),
    
    // Step 3: Prepare the file selection and date tracking in one step
    ProcessedFiles = Table.AddColumn(
        Table.Sort(
            Table.AddColumn(Source, "Date_Modified", each DateTime.From([#"Date modified"]), type datetime),
            {{"Date_Modified", Order.Descending}}
        ),
        "FileDetails", 
        each [
            Name = [Name],
            ModifiedDate = [#"Date modified"],
            FullPath = FolderPath & "\" & [Name],
            FileExtension = Text.Lower(Text.End([Name], 4))
        ]
    ),
    
    // Step 4: Select the most recent file
    LatestFileRecord = ProcessedFiles{0}[FileDetails],
    
    // Variable for the sheet name
    SheetName = Text.BeforeDelimiter(LatestFileRecord[Name], "."),
    
    // Step 5: Load data based on file type
    SheetData = 
        if LatestFileRecord[FileExtension] = ".csv" then 
            let
                // Read the CSV content
                CsvContent = Csv.Document(File.Contents(LatestFileRecord[FullPath]), [Delimiter=",", Encoding=1252, QuoteStyle=QuoteStyle.None]),
                // Count the number of columns
                ColumnCount = Table.ColumnCount(CsvContent)
            in
                // Load the CSV with the dynamically counted number of columns
                Csv.Document(File.Contents(LatestFileRecord[FullPath]), [Delimiter=",", Columns=ColumnCount, Encoding=1252, QuoteStyle=QuoteStyle.None])
        else if LatestFileRecord[FileExtension] = ".xlsb" then 
            Excel.Workbook(File.Contents(LatestFileRecord[FullPath]), null, true){0}[Data]
        else 
            Excel.Workbook(File.Contents(LatestFileRecord[FullPath])){[Item=SheetName, Kind="Sheet"]}[Data],
    
    // Step 6: Promote headers for all file types
    PromotedHeaders = Table.PromoteHeaders(SheetData, [PromoteAllScalars=true]),
    
    // Step 7: Add the "DataSourceDate" column with the modified date in "dd-mm-yy" format
    AddDateSourcedate = Table.AddColumn(
        PromotedHeaders, 
        "DataSourceDate", 
        each Date.ToText(DateTime.Date(LatestFileRecord[ModifiedDate]), "dd-MM-yy")
    ),
    
    // Step 8: Change column types
    ChangedType = Table.TransformColumnTypes(
        AddDateSourcedate,
        {{"DataSourceDate", type date}}
    )
in
    // Output the final table with the promoted headers and added "DataSourceDate" column
    ChangedType

